CC = gcc
CFLAGS = -Wall -Wextra -std=c11 -g
OBJS = main.o arquivo.o carga.o
BIN = seguradoras

all: $(BIN)

$(BIN): $(OBJS)
	$(CC) $(CFLAGS) -o $(BIN) $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(BIN) seguradoras.dat seguradoras_tmp.dat .idx_insere.txt .idx_remove.txt

.PHONY: all clean